"""Stable adapter-neutral application contracts and public errors."""

from bundlewalker.application.contracts import (
    MAX_CONCEPT_PAGE_SIZE,
    MAX_INLINE_SOURCE_CHARACTERS,
    MAX_QUESTION_CHARACTERS,
    MAX_SEARCH_CHARACTERS,
    MAX_SOURCE_NAME_CHARACTERS,
    AnswerResult,
    ConceptContent,
    ConceptPage,
    ConceptSearchResult,
    ConceptSummaryResult,
    IngestionResult,
    InlineSource,
    LintResult,
    MutationResult,
    PendingReviewResult,
    PendingReviewSummary,
    RefreshResult,
    ReviewResult,
    SynthesisResult,
    WorkspaceStatus,
)
from bundlewalker.application.errors import (
    ApplicationError,
    ApplicationErrorCode,
    translate_error,
)
from bundlewalker.application.facade import ApplicationDependencies, WorkspaceApplication

__all__ = [
    "MAX_CONCEPT_PAGE_SIZE",
    "MAX_INLINE_SOURCE_CHARACTERS",
    "MAX_QUESTION_CHARACTERS",
    "MAX_SEARCH_CHARACTERS",
    "MAX_SOURCE_NAME_CHARACTERS",
    "AnswerResult",
    "ApplicationDependencies",
    "ApplicationError",
    "ApplicationErrorCode",
    "ConceptContent",
    "ConceptPage",
    "ConceptSearchResult",
    "ConceptSummaryResult",
    "IngestionResult",
    "InlineSource",
    "LintResult",
    "MutationResult",
    "PendingReviewResult",
    "PendingReviewSummary",
    "RefreshResult",
    "ReviewResult",
    "SynthesisResult",
    "WorkspaceApplication",
    "WorkspaceStatus",
    "translate_error",
]
